let autos=[
{
    marca:'Ford',
    modelo:'Fiesta',
    precio:150000,
    km:200,
    color:'Azul',
    cuotas:12,
    anio:2019,
    patente:'APL123',
    vendido:false,
},
{
    marca:'Toyota',
    modelo:'Corolla',
    precio:100000,
    km:0,
    color:'Blanco',
    cuotas:14,
    anio:2019,
    patente:'JJK116',
    vendido:false,
},{
    marca:'Chevrolet',
    modelo:'Spark',
    precio:50000,
    km:50,
    color:'Gris',
    cuotas:14,
    anio:2019,
    patente:'GCN271',
    vendido:false,
}
]
module.exports = autos